spring.application.name=Java6

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java5;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456aA@

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.jwt.secret=1df72705de7c0218519263bf94b8faa9b13837c788d5537f88fd1fc08be6af44
app.jwt.expiration-ms=86400000
