spring.application.name=Java6

spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}

app.upload.product-image-dir=${UPLOAD_PRODUCT_IMAGE_DIR}
